# Generated by Django 5.0.1 on 2026-01-10 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', '💬 Nova poruka'), ('trade_request', '🤝 Zahtev za razmenu'), ('trade_accepted', '✅ Razmena prihvaćena'), ('trade_rejected', '❌ Razmena odbljena'), ('review', '⭐ Nova recenzija'), ('offer_liked', '❤️ Ponuda vam se dopala'), ('offer_viewed', '👁️ Neko pogledao vašu ponudu')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.offer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.trade')),
            ],
            options={
                'verbose_name': 'Notifikacija',
                'verbose_name_plural': 'Notifikacije',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx')],
            },
        ),
    ]
