# Generated by Django 5.0.1 on 2026-01-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', '💬 Nova poruka'), ('trade_request', '🤝 Zahtev za razmenu'), ('trade_accepted', '✅ Razmena prihvaćena'), ('trade_rejected', '❌ Razmena odbljena'), ('review', '⭐ Nova recenzija'), ('offer_liked', '❤️ Ponuda vam se dopala'), ('offer_viewed', '👁️ Neko pogledao vašu ponudu'), ('trade', '🤝 Razmena')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='offer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_offer1', to='core.offer'),
        ),
    ]
