# Generated by Django 5.0.1 on 2026-01-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='wants_to_buy',
            field=models.BooleanField(default=False),
        ),
    ]
